// Generated by CoffeeScript 1.9.0
(function() {
  var app;

  app = angular.module('DrillApp');

  app.factory('QuestionFactory', function(AnswerFactory) {
    return {
      createQuestion: function(body, id) {
        var Question;
        Question = function(body, id) {
          this.body = body;
          this.id = id;
          this.explanation = false;
          this.answers = [];
          this.scoreLog = [];
          this.addAnswer = function(body, correct, id) {
            var answer;
            answer = AnswerFactory.createAnswer(body, correct, id);
            return this.answers.push(answer);
          };
          this.appendToLastAnswer = function(line) {
            return this.answers[this.answers.length - 1].append(line);
          };
          this.totalCorrect = function() {
            var answer, x, _i, _len, _ref;
            x = 0;
            _ref = this.answers;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              answer = _ref[_i];
              if (answer.correct) {
                x++;
              }
            }
            return x;
          };
          this.correct = function() {
            var answer, x, _i, _len, _ref;
            x = 0;
            _ref = this.answers;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              answer = _ref[_i];
              if (answer.checked && answer.correct) {
                x++;
              }
            }
            return x;
          };
          this.incorrect = function() {
            var answer, x, _i, _len, _ref;
            x = 0;
            _ref = this.answers;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              answer = _ref[_i];
              if (answer.checked && !answer.correct) {
                x++;
              }
            }
            return x;
          };
          this.missed = function() {
            var answer, x, _i, _len, _ref;
            x = 0;
            _ref = this.answers;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              answer = _ref[_i];
              if (!answer.checked && answer.correct) {
                x++;
              }
            }
            return x;
          };
          this.grade = function(grader) {
            var grade, time;
            grade = grader(this);
            time = this.hasOwnProperty('timeLeft') ? this.timeLeft : 0;
            this.scoreLog.push({
              score: grade.score,
              total: grade.total,
              timeLeft: time
            });
            return grade;
          };
          this.loadExplanation = function(expl) {
            if (expl.hasOwnProperty(this.id)) {
              this.explanation = expl[this.id];
              return this.hasExplanations = true;
            }
          };
        };
        return new Question(body, id);
      }
    };
  });

  app.factory('AnswerFactory', function() {
    return {
      createAnswer: function(body, correct, id) {
        var Answer;
        Answer = function(body, correct, id) {
          this.body = body.trim();
          this.id = id;
          this.correct = !!correct;
          this.checked = false;
          this.append = function(line) {
            return this.body += '\n\n' + line.trim();
          };
        };
        return new Answer(body, correct, id);
      }
    };
  });

  app.factory('StatsFactory', function() {
    return {
      createStats: function() {
        var Stats;
        Stats = function() {
          this.correct = 0;
          this.partial = 0;
          this.incorrect = 0;
          this.score = 0;
          this.totalPoints = 0;
          this.totalQuestions = function() {
            return this.correct + this.incorrect + this.partial;
          };
          this.pcOfQuestions = function(num) {
            if (this.totalQuestions()) {
              return Math.round(num * 100 / this.totalQuestions());
            } else {
              return 0;
            }
          };
          this.pcScore = function() {
            if (this.totalPoints) {
              return Math.round(this.score * 100 / this.totalPoints);
            } else {
              return 0;
            }
          };
        };
        return new Stats();
      }
    };
  });

  app.factory('ViewFactory', function() {
    return {
      createView: function() {
        var View;
        View = function() {
          this.current = 'first';
          this.isFirst = function() {
            return this.current === 'first';
          };
          this.isNotGraded = function() {
            return this.current === 'question';
          };
          this.isGraded = function() {
            return this.current === 'graded';
          };
          this.isQuestion = function() {
            return this.isGraded() || this.isNotGraded();
          };
          this.isFinal = function() {
            return this.current === 'end';
          };
        };
        return new View();
      }
    };
  });

}).call(this);
